# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71d6b0e031d8013ceed229783a408f68b707f833a078988a19bdc906db009eca851e03eb5dade4d6cc115ca883b3c1bb8b61e97a61b5c6f390710d8755ad1238

test:
  secret_key_base: adfd82532de4d1695a2af7fc16b25d5846285ba2df3b979ed0788bccb38855abfd79236cacf7ceb707bdbc6cda99b0ea6834832381a5977dfedaa4a3a15f48b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
